import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Derham Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* no index */}
        <meta name="robots" content="noindex" />
      </head>
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
